### PR TITLE
fix: typo in README

### PR DESCRIPTION
**Pull request by storopoli**
Just a small typo.

### CODE REVIEW

**Comment by i5hi** [comment]
Thanks @storopoli

**Comment by i5hi** [comment]
Build is failing with this error:

```Run cargo build --features default
    Updating git repository `[https://github.com/BlockstreamResearch/rust-secp256k1-zkp.git`](https://github.com/BlockstreamResearch/rust-secp256k1-zkp.git%60)
error: failed to load source for dependency `secp256k1-zkp`

Caused by:
  Unable to update https://github.com/BlockstreamResearch/rust-secp256k1-zkp.git?rev=60e631c24588a0c9e271badd61959294848c665d

Caused by:
  revspec '60e631c24588a0c9e271badd61959294848c665d' not found; class=Reference (4); code=NotFound (-3)
Error: Process completed with exit code 101.
```

You may not be in sync with the `trunk` branch.

**Comment by storopoli** [comment]
> You may not be in sync with the `trunk` branch.

How? I am doing a 2-line diff on a markdown file.
This is an error in your CI on rust fmt and `cargo build`.
I don't think your Rust codebase uses `README.md` for anything.

**Review by michael1011 — APPROVED** [review]
>  I don't think your Rust codebase uses README.md for anything.

It doesn't but CI used to fail on the commit you based your branch on. Should be good to merge regardless

**Comment by i5hi** [comment]
> > You may not be in sync with the `trunk` branch.
> 
> How? I am doing a 2-line diff on a markdown file. This is an error in your CI on rust fmt and `cargo build`. I don't think your Rust codebase uses `README.md` for anything.

Yes, its just a doc update and rust doesn't depend on it.

It was just to let you know that your fork is not in sync with the latest.

In the future please be in sync before making a PR. It helps.

Cheers!

**Pull request merged**
